version: '2'

services:

  web:
    links:
      db:postgres
      elasticsearch:elasticsearch
    volumes:
       - /var/www/html/sites
    ports:
       - "3000:80"
  db:
    image:  wnameless/postgresql-phppgadmin

  elasticsearch:
    image: elasticsearch

  