version: '2'

services:
  web:
    build: .
    links:
     - db:postgres
     - elasticsearch:elasticsearch
    volumes:
      - ./tripal:/var/www/html/sites/all/modules/tripal
      - ./modules:/var/www/html/sites/all/modules/tripal_extensions
    ports:
      - "3000:80"
    entrypoint: /bin/bash

  db:
    image:  wnameless/postgresql-phppgadmin
    volumes: 
      - psql:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tripal
  elasticsearch:
    image: elasticsearch
volumes:
  psql:



  